name: chat_video_generator
description: A Flutter application that generates chat videos.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ffmpeg_kit_flutter: ^6.0.3
  path_provider: ^2.1.1
  permission_handler: ^10.2.0
  device_info_plus: ^9.1.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
